version: '3.8'

services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile-backend
      args:
        - CUSTOM_HOST=${CUSTOM_HOST:-localhost}
    ports:
      - "9428:9428"
    volumes:
      - backend-data:/app/data
    networks:
      - app-network
    environment:
      - ENVIRONMENT=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9428/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile-frontend
      args:
        - CUSTOM_HOST=${CUSTOM_HOST:-localhost}
    ports:
      - "8080:8080"
    volumes:
      - frontend-data:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - API_URL=http://backend:9428
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3

  tests:
    build:
      context: ./front-end
      dockerfile: Dockerfile-tests
    depends_on:
      - backend
      - frontend
    volumes:
      - test-results:/app/test-results
    networks:
      - app-network
    #ports:
    #  - "9323:9323
    environment:
      - API_URL=http://backend:9428

networks:
  app-network:

volumes:
  backend-data:
  frontend-data:
  test-results:
